// products.jsx
const products = [
  {
    id: 1,
    name: 'Product 1',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 19.99,
    category: 'ANTI CANCER',
    type: 'TABLET',
    tags: ['tag1', 'tag2'],
    manufacturer: 'Manufacturer A',
    inventory: {
      quantity: 100,
      inStock: true,
    },
    imageUrl: 'https://marketplace.canva.com/EAFWqgieqss/1/0/1600w/canva-blue-and-peach-gradient-facebook-profile-picture-oBy0jAd4JFY.jpg',
  },
  {
    id: 2,
    name: 'Product 2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 24.99,
    category: 'ANTI CANCER',
    type: 'INJECTION',
    tags: ['tag3', 'tag4'],
    manufacturer: 'Manufacturer B',
    inventory: {
      quantity: 50,
      inStock: false,
    },
    imageUrl: 'https://photo-works.net/images/tutorial/how-ot-make-picture-black-and-white-after.jpg',
  },
  {
    id: 3,
    name: 'Product 3',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 29.99,
    category: 'ANTI HIV',
    type: 'CAPSULE',
    tags: ['tag5', 'tag6'],
    manufacturer: 'Manufacturer C',
    inventory: {
      quantity: 75,
      inStock: true,
    },
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-vmqbjARLbVszo2pP66XHgEYTd5wq186TPdF10Ng-Lzw4V_v5JHacpAl1JwYH2jn7j-g&usqp=CAU',
  },
  {
    id: 4,
    name: 'Product 4',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 14.99,
    category: 'PAIN RELIEF',
    type: 'TABLET',
    tags: ['tag7', 'tag8'],
    manufacturer: 'Manufacturer D',
    inventory: {
      quantity: 120,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_4',
  },
  {
    id: 5,
    name: 'Product 5',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 39.99,
    category: 'SKIN CARE',
    type: 'CREAM',
    tags: ['tag9', 'tag10'],
    manufacturer: 'Manufacturer E',
    inventory: {
      quantity: 90,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_5',
  },
  {
    id: 6,
    name: 'Product 6',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 29.99,
    category: 'VITAMINS',
    type: 'CAPSULE',
    tags: ['tag11', 'tag12'],
    manufacturer: 'Manufacturer F',
    inventory: {
      quantity: 60,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_6',
  },
  {
    id: 7,
    name: 'Product 7',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 19.99,
    category: 'HEART HEALTH',
    type: 'TABLET',
    tags: ['tag13', 'tag14'],
    manufacturer: 'Manufacturer G',
    inventory: {
      quantity: 80,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_7',
  },
  {
    id: 8,
    name: 'Product 8',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 44.99,
    category: 'DIGESTIVE',
    type: 'SYRUP',
    tags: ['tag15', 'tag16'],
    manufacturer: 'Manufacturer H',
    inventory: {
      quantity: 40,
      inStock: false,
    },
    imageUrl: 'URL_TO_IMAGE_8',
  },
  {
    id: 9,
    name: 'Product 9',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 34.99,
    category: "WOMEN'S HEALTH",
    type: 'CAPSULE',
    tags: ['tag17', 'tag18'],
    manufacturer: 'Manufacturer I',
    inventory: {
      quantity: 110,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_9',
  },
  {
    id: 10,
    name: 'Product 10',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 19.99,
    category: 'COLD & FLU',
    type: 'TABLET',
    tags: ['tag19', 'tag20'],
    manufacturer: 'Manufacturer J',
    inventory: {
      quantity: 30,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_10',
  },
  {
    id: 11,
    name: 'Product 11',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 24.99,
    category: 'DIABETES',
    type: 'INSULIN',
    tags: ['tag21', 'tag22'],
    manufacturer: 'Manufacturer K',
    inventory: {
      quantity: 65,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_11',
  },
  {
    id: 12,
    name: 'Product 12',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 29.99,
    category: 'ALLERGY',
    type: 'SYRUP',
    tags: ['tag23', 'tag24'],
    manufacturer: 'Manufacturer L',
    inventory: {
      quantity: 85,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_12',
  },
  {
    id: 13,
    name: 'Product 13',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 19.99,
    category: 'BONE HEALTH',
    type: 'TABLET',
    tags: ['tag25', 'tag26'],
    manufacturer: 'Manufacturer M',
    inventory: {
      quantity: 95,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_13',
  },
  {
    id: 14,
    name: 'Product 14',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 24.99,
    category: 'EYE CARE',
    type: 'DROPS',
    tags: ['tag27', 'tag28'],
    manufacturer: 'Manufacturer N',
    inventory: {
      quantity: 55,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_14',
  },
  {
    id: 15,
    name: 'Product 15',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 29.99,
    category: 'SLEEP AID',
    type: 'CAPSULE',
    tags: ['tag29', 'tag30'],
    manufacturer: 'Manufacturer O',
    inventory: {
      quantity: 70,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_15',
  },
  {
    id: 9,
    name: 'Product 9',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 34.99,
    category: "WOMEN'S HEALTH",
    type: 'CAPSULE',
    tags: ['tag17', 'tag18'],
    manufacturer: 'Manufacturer I',
    inventory: {
      quantity: 110,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_9',
  },
  {
    id: 10,
    name: 'Product 10',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 19.99,
    category: 'COLD & FLU',
    type: 'TABLET',
    tags: ['tag19', 'tag20'],
    manufacturer: 'Manufacturer J',
    inventory: {
      quantity: 30,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_10',
  },
  {
    id: 11,
    name: 'Product 11',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 24.99,
    category: 'DIABETES',
    type: 'INSULIN',
    tags: ['tag21', 'tag22'],
    manufacturer: 'Manufacturer K',
    inventory: {
      quantity: 65,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_11',
  },
  {
    id: 12,
    name: 'Product 12',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 29.99,
    category: 'ALLERGY',
    type: 'SYRUP',
    tags: ['tag23', 'tag24'],
    manufacturer: 'Manufacturer L',
    inventory: {
      quantity: 85,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_12',
  },
  {
    id: 13,
    name: 'Product 13',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 19.99,
    category: 'BONE HEALTH',
    type: 'TABLET',
    tags: ['tag25', 'tag26'],
    manufacturer: 'Manufacturer M',
    inventory: {
      quantity: 95,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_13',
  },
  {
    id: 14,
    name: 'Product 14',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 24.99,
    category: 'EYE CARE',
    type: 'DROPS',
    tags: ['tag27', 'tag28'],
    manufacturer: 'Manufacturer N',
    inventory: {
      quantity: 55,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_14',
  },
  {
    id: 15,
    name: 'Product 15',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: 29.99,
    category: 'SLEEP AID',
    type: 'CAPSULE',
    tags: ['tag29', 'tag30'],
    manufacturer: 'Manufacturer O',
    inventory: {
      quantity: 70,
      inStock: true,
    },
    imageUrl: 'URL_TO_IMAGE_15',
  },
];

export default products;
